[plugin]
prepend_previewers = [
  { url = "*/", run = "eza-preview" },
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { name = "*.{bin,exe}", run = "hevi" },
]


[manager]
show_hidden = true

[opener]
pdf = [{ run = 'zathura "$@"', desc = "Open PDF" }]
edit = [{ run = 'nvim "$@"', block = true, desc = "Open in Neovim" }]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "image/*", run = 'xdg-open "$@"' },
  { mime = "application/pdf", use = "pdf" },
  # Fallback → everything else
  { name = "*.c", use = "edit" },
  { name = "*.cpp", use = "edit" },
  { name = "*.h", use = "edit" },
  { name = "*.hpp", use = "edit" },
  { name = "*.js", use = "edit" },
  { name = "*.ts", use = "edit" },
  { name = "*.py", use = "edit" },
  { name = "*.lua", use = "edit" },
  { name = "*.json", use = "edit" },
  { name = "*.sh", use = "edit" },
  { name = "*.html", use = "edit" },
  { name = "*.css", use = "edit" },
  { name = "*.md", use = "edit" },
  { name = "*", use = "open" },

]
