[plugin]
prepend_previewers = [
  { url = "*/", run = "eza-preview" },
  { url = "*.tar*", run = 'piper --format=url -- tar tf "$1"' },
  { url = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { name = "*.{bin,exe}", run = "hevi" },
]

[manager]
show_hidden = true
